
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./robot.glb
-->




    <script>
				
	
	
  
        import { T } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        let {
					fallback,
          error,
          children,
          ref = $bindable(),
          ...props
        } = $props()

				

				

        

        const gltf = useGltf('/robot.glb')

    
    </script>

		<T.Group bind:ref dispose={false} {...props}>
			{#await gltf}
        {@render fallback?.()}
			{:then gltf}
				<T.Group rotation={[0,0,.8]} position={[0, -.37, 0.0,]} scale={0.02} >
<T is={gltf.nodes.antena_bottom} />
<T is={gltf.nodes.neutral_bone} />
<T.SkinnedMesh geometry={gltf.nodes.robot.geometry} material={gltf.materials['Plane_Baked.001']} skeleton={gltf.nodes.robot.skeleton} />

</T.Group>

			{:catch err}
        {@render error?.({ error: err })}
			{/await}

      {@render children?.({ ref })}
		</T.Group>
	
