
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./robot.glb -o src/lib/Robot.svelte
-->




    <script>
				
	
	
  
        import { T } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        let {
					fallback,
          error,
          children,
          ref = $bindable(),
          ...props
        } = $props()

				

				

        

        const gltf = useGltf('/robot.glb')

    
    </script>

		<T.Group bind:ref dispose={false} {...props}>
			{#await gltf}
        {@render fallback?.()}
			{:then gltf}
				<T.Group position={[0.04, 1.57, 0.06,]} scale={0.39} >
<T is={gltf.nodes.antena_bottom} />
<T is={gltf.nodes.neutral_bone} />
<T.SkinnedMesh geometry={gltf.nodes.robot.geometry} material={gltf.materials['Plane_Baked.001']} skeleton={gltf.nodes.robot.skeleton} />

</T.Group>
<T.PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={22.9} position={[30.36, 0.93, 0.04,]} rotation={[1.53, 1.4, -1.53,]} />

			{:catch err}
        {@render error?.({ error: err })}
			{/await}

      {@render children?.({ ref })}
		</T.Group>
	